### ISSUE TITLE
Backgroundlayers based on geopunt are no longer visible

### ISSUE THREAD

**Issue by gpoilvet** [osmbe/play#11]
The layers:
-Luchtfoto(VL)
-Basiskaart GRB (VL)
-AIV Hillshade (strong, VL)
-AIV Hillshade (soft, VL)
-Frickx (1745, VL)
-Villaret (1745, VL)
- Ferraris (1777, VL)
- Atlas der Buurtwegen (1840, VL)
- Vandermaelen (1846-1854, VL)
- Popp (1842-1854, VL)
- Ferraris forest cover (VL)

are no longer visible since the geopunt update. Could the links be fixed so that the layers once again become visible?
Thanks :)

**Comment by jbelien** [comment]
Solved! ✅
