### ISSUE TITLE
HIstorical web map services from NGI have been changed into web map tile services....

### ISSUE THREAD

**Issue by StevenClays** [osmbe/play#14]
Beste,

 

De url is inderdaad aangepast naar [wmts.ngi.be](http://wmts.ngi.be/) ipv [www.ngi.be](http://www.ngi.be/).

 

Met vriendelijke groeten,

Cartesius webteam

 

From: Steven Clays <[steven.clays@tragewegen.be](mailto:steven.clays@tragewegen.be)>
Sent: Wednesday, 24 April 2024 09:31
To: Cartesius <[cartesius@ngi.be](mailto:cartesius@ngi.be)>
Subject: Historische kaartenset

 

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

 

Geachte,

 

het lijkt erop dat de webservices van een hele reeks historische kaarten momenteel niet beschikbaar zijn.

 

Het gaat onder meer over:

NGI Basiskaart, 1873

NGI Basiskaart, 1904
NGI Basiskaart, 1939
NGI Basiskaart, 1969
NGI Basiskaart, 1981
NGI Basiskaart, 1989

 

Is dit correct of zouden de links ernaar toe aangepast zijn? Alvast bedankt voor de opvolging!

 

Met vriendelijke groeten,

Steven Clays
Inhoudelijk coördinator

**Comment by joostschouppe** [comment]
De oude URLs waren iets als https://www.ngi.be/tiles/arcgis/rest/services/seamless_carto__default__3857__140/MapServer/tile/13/2749/4200/
Als ik daar gewoon https://wmts.ngi.be/tiles/arcgis/rest/services/seamless_carto__default__3857__140/MapServer/tile/13/2749/4200/ van maak, dan werkt het niet.
Via de Gallerij op cartesius.be vind ik de kaarten wel terug, maar hun ArcGIS webkaarten zijn ook nog kapot :)

**Comment by StevenClays** [comment]
Ja, ik merkte het. We maakten opnieuw een melding, maar misschien is het
goed dat jullie dat ook doen?

Steven Clays
*Inhoudelijk coördinator*



*A* Dendermondsesteenweg 50, 9000 Gent
*T* 09 / 331 59 21
*M* 0494 / 54 20 92
*W *www.tragewegen.be
Graag meer weten over trage wegen?

Abonneer je op onze maandelijkse nieuwsbrief
<https://hubspot.tragewegen.be/abonneer-je-op-het-e-zine>.


Op wo 24 apr 2024 om 17:01 schreef Joost ***@***.***>:

**Comment by StevenClays** [comment]
Deze urls werken wel (wel als XYZ-laag):

https://wmts.ngi.be/arcgis/rest/services/seamless_carto__default__3857__1220/MapServer/tile/{z}/{y}/{x}

Dus die 'tiles' moest er van tussen.

https://www.ngi.be/tiles/arcgis/rest/services/seamless_carto__default__3857__140/MapServer/tile/{z}/{y}/{x}


Alvast bedankt om dit aan te passen!

Steven Clays
*Inhoudelijk coördinator*



*A* Dendermondsesteenweg 50, 9000 Gent
*T* 09 / 331 59 21
*M* 0494 / 54 20 92
*W *www.tragewegen.be
Graag meer weten over trage wegen?

Abonneer je op onze maandelijkse nieuwsbrief
<https://hubspot.tragewegen.be/abonneer-je-op-het-e-zine>.


Op wo 24 apr 2024 om 17:34 schreef Steven Clays ***@***.***

**Comment by joostschouppe** [comment]
Thanks Steven!
I fixed it here https://github.com/osmbe/play/commit/b40896546ff5f0670af6cf5c30d752b1a8d9e0bb
And it seems to work now.
