### ISSUE TITLE
Add classic topomap NGI 2000 / add geolocator / add strava

### ISSUE THREAD

**Issue by StevenClays** [osmbe/play#4]
Is it possible to add the topomap (2000) to the historical maps?
https://topomapviewer.ngi.be/?l=nl&x=629911.03&y=660643.61&zoom=8&baseLayer=top10r

**Comment by StevenClays** [comment]
Is it possible to add a geolocator to play.osm.be/historischekaart.html?

**Comment by StevenClays** [comment]
Strava heatmap is up and running again, so is it possible to add this to  play.osm.be/historischekaart.html as an overlay? 
https://anygis.ru/api/v1/Tracks_Strava_All_HD/{$x}/{$y}/{$z}

**Comment by jbelien** [comment]
I splitted this in 3 different issues!
